context:
  active-host: cloud.getdbt.com
  active-project: '358013'
default:
  outputs:
    dev:
      dbname: postgres    
      host: vinted.cl2cus64cwps.eu-north-1.rds.amazonaws.com
      pass: "9121759591mM!"
      port: 5432
      schema: dbt_msilva      
      threads: 4        
      type: postgres
      user: postgres      
  target: dev      
projects:
- project-name: Analytics
  project-id: '358013'
  account-name: ST
  account-id: '251485'
  account-host: cloud.getdbt.com
  token-name: cloud-cli-15a5
  token-value: dbtu_Hn5R3gQjWzDZhn2qlUBfnVMkxAJDsHrZEvnECtBYLeR4Fs7WKg
version: "1"
